import Head from "next/head";
import styles from "../../../../styles/Home.module.css";
import Layout from "../../../../component/layout";
import {apiRequest} from "../../../../util/apiRequest";
import { useRouter } from "next/router";
import React, { useState, ChangeEvent, useEffect } from "react";
import Table from "@mui/material/Table";
import TableHead from "@mui/material/TableHead";
import TableRow from "@mui/material/TableRow";
import TableCell from "@mui/material/TableCell";
import TableBody from "@mui/material/TableBody";
import Button from "@mui/material/Button";
import IconButton from "@mui/material/IconButton";
import ModeEditIcon from "@mui/icons-material/ModeEdit";
import DeleteIcon from "@mui/icons-material/Delete";
import BuildCircleIcon from "@mui/icons-material/BuildCircle";
import Grid from "@mui/material/Grid";
import Link from "@mui/material/Link";

export default function PortalDaNota() {
  const [aluno, setAluno] = useState<any>([]);
  const [notas, setNotas] = useState<any>([]);
  const [open, setOpen] = useState(false);
  const router = useRouter();
  async function getNotas() {
    const resNotas = await apiRequest.get(
      "atividade/listAllScores/" + router.query.idAtividade
    );
    if (resNotas.data) {
      setNotas(resNotas.data);
    }
  }
  useEffect(() => {
    getNotas();
  }, []);

  return (
    <div className={styles.container}>
      <Head>
        <title>Galdi</title>
        <meta name="description" content="Generated by meio a meio" />
      </Head>
      <Layout>
        <main className={styles.main}>
          <p className={styles.description}>Notas</p>
          <div
            style={{
              alignItems: "center",
              display: "flex",
              flexDirection: "column",
            }}
          >
            <Table
              sx={{ minWidth: 650 }}
              size="small"
              aria-label="a dense table"
            >
              <TableHead>
                <TableRow>
                  <TableCell align="center">Aluno</TableCell>
                  <TableCell align="center">Nota</TableCell>
                </TableRow>
              </TableHead>
              <TableBody>
                {notas.map((row, index) => (
                  <TableRow key={index}>
                    <TableCell align="center">{row.nome_completo}</TableCell>
                    <TableCell align="center">{row.nota || ""}</TableCell>
                  </TableRow>
                ))}
              </TableBody>
            </Table>

            <Button
              variant="outlined"
              onClick={() => router.push({pathname: "cadastro", query: {atividade_id: router.query.idAtividade, nome: router.query.nomeAtividade}})}
              sx={{ alignSelf: "center" }}
            >
              Cadastrar
            </Button>
            <Grid container justifyContent="center">
              <Grid item>
                <Link onClick={() => router.back()} variant="body2">
                  Retornar ao Menu Principal
                </Link>
              </Grid>
            </Grid>
          </div>
        </main>
      </Layout>
    </div>
  );
}
