import Head from "next/head";
import styles from "../../../styles/Home.module.css";
import Layout from "../../../component/layout";
import {apiRequest} from "../../../util/apiRequest";
import { useRouter } from "next/router";
import React, { useState, ChangeEvent, useEffect } from "react";
import Table from "@mui/material/Table";
import TableHead from "@mui/material/TableHead";
import TableRow from "@mui/material/TableRow";
import TableCell from "@mui/material/TableCell";
import TableBody from "@mui/material/TableBody";
import Button from "@mui/material/Button";
import IconButton from "@mui/material/IconButton";
import ModeEditIcon from "@mui/icons-material/ModeEdit";
import BuildCircleIcon from "@mui/icons-material/BuildCircle";

export default function PortalDaAtividadeTurma() {
  const [atividadeTurma, setAtividadeTurma] = useState<any>([]);
  const router = useRouter();
  async function getAtividadesTurma(){
    const resAtividadesTurma = await apiRequest.get("atividade/" + router.query.detalhes);
    if (resAtividadesTurma.data) {
      setAtividadeTurma(resAtividadesTurma.data);
    }
  }
  useEffect(() => {
    getAtividadesTurma();
  }, []);

  return (
    <div className={styles.container}>
      <Head>
        <title>Galdi</title>
        <meta name="description" content="Generated by meio a meio" />
      </Head>
      <Layout>
        <main className={styles.main}>
          <p className={styles.description}>Lista de Atividades</p>
          <div
            style={{
              alignItems: "center",
              display: "flex",
              flexDirection: "column",
            }}
          >
            <Table
              sx={{ minWidth: 650 }}
              size="small"
              aria-label="a dense table"
            >
              <TableHead>
                <TableRow>
                  <TableCell align="center">Nome</TableCell>
                </TableRow>
              </TableHead>
              <TableBody>
                {atividadeTurma.map((row, index) => (
                  <TableRow key={index}>
                    <TableCell align="center">
                      {row.nome}
                      <IconButton
                        aria-label="expand row"
                        size="small"
                        onClick={() =>
                          router.push({
                            pathname: "atividade/notas/listar",
                            query: { idAtividade: row.id, nomeAtividade: row.nome },
                          })
                        }
                      >
                        <BuildCircleIcon color="primary" />
                      </IconButton>
                    </TableCell>
                    <TableCell align="center">
                      {row.isTest}
                    </TableCell>
                  </TableRow>
                ))}
              </TableBody>
            </Table>
            <Button
              variant="outlined"
              onClick={() => router.push({pathname: "atividade/cadastro", query: atividadeTurma})}
              sx={{ alignSelf: "center" }}
            >
              Cadastrar
            </Button>
          </div>
        </main>
      </Layout>
    </div>
  );
}
