import React, { useState, ChangeEvent, useEffect } from "react";
import Avatar from "@mui/material/Avatar";
import Button from "@mui/material/Button";
import CssBaseline from "@mui/material/CssBaseline";
import TextField from "@mui/material/TextField";
import FormControlLabel from "@mui/material/FormControlLabel";
import Checkbox from "@mui/material/Checkbox";
import Link from "@mui/material/Link";
import Grid from "@mui/material/Grid";
import Box from "@mui/material/Box";
import LockOutlinedIcon from "@mui/icons-material/LockOutlined";
import Typography from "@mui/material/Typography";
import Container from "@mui/material/Container";
import { createTheme, ThemeProvider } from "@mui/material/styles";
import Image from "next/image";
import Head from "next/head";
import { useRouter } from "next/router";
import apiRequest from "../../util/apiRequest";
import {
  Select,
  MenuItem,
  SelectChangeEvent,
  FormHelperText,
} from "@mui/material";
import InputLabel from "@mui/material/InputLabel";
import { LocalizationProvider } from "@mui/x-date-pickers/LocalizationProvider";
import { DatePicker } from "@mui/x-date-pickers/DatePicker";
import { AdapterDateFns } from "@mui/x-date-pickers/AdapterDateFns";
const theme = createTheme();

export default function Cadastro({
  listaDisciplinas: listaDisciplinas,
  listaProfessores: listaProfessores,
  listaCursos: listaCursos,
  error,
}) {
  const [data, setData] = useState<any>({});
  const [errors, setErrors] = useState<any>({});
  const [professor, setProfessor] = useState<any>([]);
  const [disciplina, setDisciplina] = useState<any>([]);
  const [curso, setCurso] = useState<any>([]);
  const router = useRouter();

  useEffect(() => {
    if (listaDisciplinas) {
      setDisciplina(listaDisciplinas);
    }
    if (listaProfessores) {
      setProfessor(listaProfessores);
    }
    if (listaCursos) {
      setCurso(listaCursos);
    }
    console.log(listaDisciplinas);
    console.log(listaProfessores);
    console.log(listaCursos);
    console.log(error);
    //erros
  }, []);
  const handleDate = (e: SelectChangeEvent<HTMLInputElement>) => {
    console.log(e);
    const formatedData = Moment(e).format("yyyy/MM/DD");
    setData({ ...data, data_de_nascimento: formatedData });
  };
  const handleSubmit = (event: React.FormEvent<HTMLFormElement>) => {
    event.preventDefault();
    console.log(data);
    if (handleCheckData()) {
      return;
    }
    apiRequest
      .post("turma", { ...data })
      .then((result) => {
        router.push("/turma/portal");
        console.log("ok");
      })
      .catch((err) => {
        console.log("errado", err);
      });
  };
  const handleText = (e: ChangeEvent<HTMLInputElement>) => {
    const clearText = e.target.value.replace(/\d/, "");
    setData({ ...data, [e.target.name]: clearText });
    let tempErrors = errors;
    delete tempErrors[e.target.name];
    setErrors(tempErrors);
  };

  const handleNumber = (e: ChangeEvent<HTMLInputElement>) => {
    const clearNumber = e.target.value.replace(/\D/, "");
    setData({ ...data, [e.target.name]: clearNumber });
  };

  const handleCheckData = () => {
    const { nome, horarios, dias, professor, disciplina } = data;
    let emptyFields: any = {};

    if (!nome || nome.length === 0) {
      emptyFields.nome = "Nome Vazio";
    }
    if (Object.keys(emptyFields).length > 0) {
      setErrors(emptyFields);
      return 1;
    }
    return 0;
  };

  return (
    <ThemeProvider theme={theme}>
      <Container component="main" maxWidth="lg">
        <CssBaseline />
        <Box
          sx={{
            marginTop: 8,
            display: "flex",
            flexDirection: "column",
            alignItems: "center",
          }}
        >
          <div>
            <Head>
              <title>Galdi</title>
              <meta name="description" content="Generated by meio a meio" />
            </Head>
            {/* <Image src= "/images/logo.jpeg" width= '600px' height= '150px'/> */}
          </div>
          <Typography component="h1" variant="h5">
            Insira os dados cadastrais da turma
          </Typography>
          <Box
            component="form"
            noValidate
            onSubmit={handleSubmit}
            sx={{ mt: 3 }}
          >
            <Grid container spacing={2}>
              <Grid item xs={12}>
                <TextField
                  required
                  error={errors.nome ? true : false}
                  helperText={errors.nome || null}
                  fullWidth
                  id="nome"
                  label="Nome da Turma"
                  name="nome"
                  autoComplete="nome"
                  onChange={handleText}
                  value={data ? data.nome : ""}
                />
              </Grid>
              <Grid item xs={3}>
                <LocalizationProvider dateAdapter={AdapterDateFns}>
                  <DatePicker
                    label="Data"
                    name="data"
                    inputFormat="dd/MM/yyyy"
                    value={data ? data.data : ""}
                    onChange={handleDate}
                    renderInput={(params) => <TextField {...params} />}
                  />
                </LocalizationProvider>
                <FormHelperText error>
                  {errors.data_de_nascimento}
                </FormHelperText>
              </Grid>
              <Grid item xs={12}>
                <InputLabel id="professor">Professor</InputLabel>
                <Select
                  fullWidth
                  onChange={(e) =>
                    setData({ ...data, professor: e.target.value })
                  }
                  label={"Professor"}
                  value={data ? data.professor : ""}
                >
                  {professor.map((i, index) => (
                    <MenuItem key={index} value={i.id}>
                      {i.nome_completo}
                    </MenuItem>
                  ))}
                </Select>
              </Grid>
              <Grid item xs={12}>
                <InputLabel id="disciplina">Disciplina</InputLabel>
                <Select
                  fullWidth
                  onChange={(e) =>
                    setData({ ...data, disciplina: e.target.value })
                  }
                  label={"Disciplina"}
                  value={data ? data.disciplina : ""}
                >
                  {disciplina.map((i, index) => (
                    <MenuItem key={index} value={i.id}>
                      {i.nome_disciplina}
                    </MenuItem>
                  ))}
                </Select>
              </Grid>
              <Grid item xs={12}>
                <InputLabel id="curso" required>
                  Curso
                </InputLabel>
                <Select
                  required
                  fullWidth
                  error={errors.curso ? true : false}
                  onChange={(e) => setData({ ...data, curso: e.target.value })}
                  label={"Curso"}
                  value={data ? data.curso : ""}
                >
                  {curso.map((i, index) => (
                    <MenuItem key={index} value={i.id}>
                      {i.nome}
                    </MenuItem>
                  ))}
                </Select>
              </Grid>
            </Grid>
            <Button
              type="submit"
              fullWidth
              variant="contained"
              sx={{ mt: 3, mb: 2 }}
            >
              Cadastrar Turma
            </Button>
            <Grid container justifyContent="center">
              <Grid item>
                <Link href="/turma/portal" variant="body2">
                  Retornar ao Menu Principal
                </Link>
              </Grid>
            </Grid>
          </Box>
        </Box>
      </Container>
    </ThemeProvider>
  );
}

export async function getServerSideProps() {
  const resProfessor = await apiRequest.get("professor"); //lista de professores
  const resDisciplina = await apiRequest.get("disciplina"); //lista de disciplinas
  const resCursos = await apiRequest.get("curso");
  console.log("aaa", resDisciplina);
  if (
    !resProfessor ||
    !resDisciplina ||
    !resCursos ||
    !resProfessor.data ||
    !resDisciplina.data ||
    !resCursos.data
  ) {
    return { props: { error: "Falha ao carregar conteúdo" } };
  }

  return {
    props: {
      listaProfessores: resProfessor.data,
      listaDisciplinas: resDisciplina.data,
      listaCursos: resCursos.data,
      error: null,
    },
  };
}
