import Head from 'next/head'
import { useRouter } from 'next/router'
import styles from '../../styles/Home.module.css'
import Link from 'next/link'
import Layout from '../../component/layout'


export default function PortalDaTurma() {
    const router = useRouter()
    return (
      <div className={styles.container}>
        <Head>
          <title>Galdi</title>
          <meta name="description" content="Generated by meio a meio" />
        </Head>
        <Layout>
        <main className={styles.main}>
          <h1 className={styles.title}>
            Enquanto não tem a tab
          </h1>

          <div className={styles.grid}>
            <Link href="/turma/aluno/listar">
            <a
              className={styles.card}
            >
              <h2>Alunos &rarr;</h2>
            </a>
            </Link>
            <Link href="/turma/professor/listar">
            <a
              className={styles.card}
            >
              <h2>Professores &rarr;</h2>
            </a>
            </Link>
            <Link href="/turma/listaPresenca/visualizar">
            <a
              className={styles.card}
            >
              <h2>Presenças &rarr;</h2>
            </a>
            </Link>
            <Link href="/turma/diario/listar">
            <a
              className={styles.card}
            >
              <h2>Diários &rarr;</h2>
            </a>
            </Link>
            <Link href="/turma/atividade/portal">
            <a
              className={styles.card}
            >
              <h2>Atividades &rarr;</h2>
            </a>
            </Link>

          </div>
        </main>
        </Layout>
      </div>
    )
}

