import type { NextPage } from "next";
import * as React from "react";
import Head from "next/head";
import { useRouter } from "next/router";
import Image from "next/image";
import styles from "../../styles/Home.module.css";
import Link from "next/link";
import Grid from "@mui/material/Grid";
import { styled } from "@mui/material/styles";
import Box from "@mui/material/Box";
import List from "@mui/material/List";
import ListItem from "@mui/material/ListItem";
import ListItemAvatar from "@mui/material/ListItemAvatar";
import ListItemIcon from "@mui/material/ListItemIcon";
import ListItemText from "@mui/material/ListItemText";
import Avatar from "@mui/material/Avatar";
import IconButton from "@mui/material/IconButton";
import FormGroup from "@mui/material/FormGroup";
import FormControlLabel from "@mui/material/FormControlLabel";
import Checkbox from "@mui/material/Checkbox";
import Typography from "@mui/material/Typography";
import FolderIcon from "@mui/icons-material/Folder";
import DeleteIcon from "@mui/icons-material/Delete";
import Button from "@mui/material/Button";
import Stack from "@mui/material/Stack";
import InboxIcon from "@mui/icons-material/Inbox";
import DraftsIcon from "@mui/icons-material/Drafts";
import ListItemButton from "@mui/material/ListItemButton";
import Divider from "@mui/material/Divider";
import Layout from '../../component/layout'

const Demo = styled("div")(({ theme }) => ({
  backgroundColor: theme.palette.background.paper,
}));

const PortalDaTurma: NextPage = () => {
  const router = useRouter();
  const [dense, setDense] = React.useState(false);
  const [secondary, setSecondary] = React.useState(false);

  return (
    <div className={styles.container}>
      <Head>
        <title>Galdi</title>
        <meta name="description" content="Generated by meio a meio" />
        <link rel="icon" href="/images/icon.png" />
      </Head>
      <Layout>
      <main className={styles.main}>
        <h1 className={styles.title}>Bem vindo(a) ao Portal da Turma</h1>

        <p className={styles.description}>
          Lista de Turmas
          {/* <code className={styles.code}>pages/index.tsx</code> */}
        </p>

        <div className={styles.grid}>
          {/* <Link href="/turma/cadastro">
            <a className={styles.card}>
              <h2>Cadastrar &rarr;</h2>
              <p>Cadastre novas turmas por meio desta opção</p>
            </a>
          </Link>
          <Link href="/turma/listar">
            <a className={styles.card}>
              <h2>Listar &rarr;</h2>
              <p>Verifique aqui todas as turmas já cadastradas</p>
            </a>
          </Link> */}
          {/* <Link href="/turma/editar">
            <a className={styles.card}>
              <h2>Editar &rarr;</h2>
              <p>Edique aqui todas a turma desejada</p>
            </a>
          </Link> */}
          {/* <Link href="/avaliacao/portal">
            <a className={styles.card}>
              <h2>Avaliações &rarr;</h2>
              <p>Informações sobre as suas avaliações</p>
            </a>
          </Link>
          <Link href="/atividade/portal">
            <a className={styles.card}>
              <h2>Atividades &rarr;</h2>
              <p>Informações sobre as suas atividades</p>
            </a>
          </Link>
          <Grid container justifyContent="center" sx={{ mt: 4 }}>
            <Grid item>
              <Link href="/docente/portal">
                {"Retornar ao Portal do Docente"}
              </Link>
            </Grid>
          </Grid> */}
          <Grid item xs={12} md={1}>
            <Demo>
              <List>
                <Link href="/disciplina/portal">
                  <ListItem disablePadding>
                    <ListItemButton>
                      <ListItemText primary="Turma A" />
                    </ListItemButton>
                  </ListItem>
                </Link>
                <Link href="/disciplina/portal">
                  <ListItem disablePadding>
                    <ListItemButton>
                      <ListItemText primary="Turma B" />
                    </ListItemButton>
                  </ListItem>
                </Link>
              </List>
            </Demo>
          </Grid>
          <Grid container justifyContent="center" sx={{ mt: 4 }}>
            <Grid item>
              <Link href="/docente/portal">
                {"Retornar ao Portal do Docente"}
              </Link>
            </Grid>
          </Grid>
          <Stack spacing={35} direction="row">
            <Button variant="outlined" href="/turma/cadastro">
              Cadastrar
            </Button>
            <Button variant="outlined" href="/turma/editar">
              Editar
            </Button>
          </Stack>
        </div>
      </main>
      </Layout>
      <footer className={styles.footer}>
        <a
          href="https://mdsreq-fga-unb.github.io/2022.1-Meio-a-Meio/"
          target="_blank"
          rel="noopener noreferrer"
        >
          Copyright © Meio a Meio
        </a>
      </footer>
    </div>
  );
};

export default PortalDaTurma;
