import type { NextPage } from "next";
import Head from "next/head";
import { useRouter } from "next/router";
import Image from "next/image";
import styles from "../../styles/Home.module.css";
import Link from "next/link";
import Grid from "@mui/material/Grid";
import Button from "@mui/material/Button";
import Stack from "@mui/material/Stack";
import ListItemButton from "@mui/material/ListItemButton";
import ListItemText from "@mui/material/ListItemText";
import List from "@mui/material/List";
import ListItem from "@mui/material/ListItem";
import { styled } from "@mui/material/styles";

const Demo = styled("div")(({ theme }) => ({
  backgroundColor: theme.palette.background.paper,
}));
const PortalDaDisciplina: NextPage = () => {
  const router = useRouter();
  return (
    <div className={styles.container}>
      <Head>
        <title>Galdi</title>
        <meta name="description" content="Generated by meio a meio" />
        <link rel="icon" href="/images/icon.png" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Bem vindo(a) ao Portal da Disciplina</h1>

        <p className={styles.description}>Lista de Disciplinas</p>

        <div className={styles.grid}>
          {/* <Link href="/disciplina/cadastro">
            <a
              className={styles.card}
            >
              <h2>Cadastrar &rarr;</h2>
              <p>
                Cadastre novas disciplinas por meio desta opção
              </p>
            </a>
            </Link>
            <Link href="/disciplina/listar">
            <a
              className={styles.card}
            >
              <h2>Listar &rarr;</h2>
              <p>
                Verifique aqui todas as disciplinas já cadastradas
              </p>
            </a>
            </Link>
            <Grid container justifyContent="center" sx={{ mt: 4 }}>
              <Grid item>
                <Link href="/docente/portal" >
                  {"Retornar ao Portal do Docente"}
                </Link>
              </Grid>
            </Grid> */}
          <Grid item xs={12} md={1}>
            <Demo>
              <List>
                <Link href="/atividade/portal">
                  <ListItem disablePadding>
                    <ListItemButton>
                      <ListItemText primary="História" />
                    </ListItemButton>
                  </ListItem>
                </Link>
                <Link href="/atividade/portal">
                  <ListItem disablePadding>
                    <ListItemButton>
                      <ListItemText primary="Geografia" />
                    </ListItemButton>
                  </ListItem>
                </Link>
              </List>
            </Demo>
          </Grid>
          <Grid container justifyContent="center" sx={{ mt: 4 }}>
            <Grid item>
              <Link href="/docente/portal">
                {"Retornar ao Portal do Docente"}
              </Link>
            </Grid>
          </Grid>
          <Stack spacing={35} direction="row">
            <Button variant="outlined" href="/disciplina/cadastro">
              Cadastrar
            </Button>
            <Button variant="outlined" href="/disciplina/editar">
              Editar
            </Button>
          </Stack>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://mdsreq-fga-unb.github.io/2022.1-Meio-a-Meio/"
          target="_blank"
          rel="noopener noreferrer"
        >
          Copyright © Meio a Meio
        </a>
      </footer>
    </div>
  );
};

export default PortalDaDisciplina;
