import Head from "next/head";
import { useRouter } from "next/router";
import styles from "../../../styles/Home.module.css";
import Grid from "@mui/material/Grid";
import Layout from "../../../component/layout";
import {apiRequest} from "../../../util/apiRequest";
import React, { useState, ChangeEvent, useEffect } from "react";
import Table from "@mui/material/Table";
import TableHead from "@mui/material/TableHead";
import TableRow from "@mui/material/TableRow";
import TableCell from "@mui/material/TableCell";
import TableBody from "@mui/material/TableBody";
import Button from "@mui/material/Button";
import IconButton from "@mui/material/IconButton";
import ModeEditIcon from "@mui/icons-material/ModeEdit";
import DeleteIcon from "@mui/icons-material/Delete";
import Link from "@mui/material/Link";

export default function PortalDoDiarioTurma() {
  const [diarioTurma, setDiarioTurma] = useState<any>([]);
  const router = useRouter();
  async function getDiariosTurma(){
    const resDiariosTurma = await apiRequest.get("turma/diarios/" + router.query.detalhes);
    if (resDiariosTurma.data) {
      setDiarioTurma(resDiariosTurma.data);
    }
  }
  useEffect(() => {
    getDiariosTurma();
  }, []);

  return (
    <div className={styles.container}>
      <Head>
        <title>Galdi</title>
        <meta name="description" content="Generated by meio a meio" />
      </Head>
      <Layout>
        <main className={styles.main}>
          <p className={styles.description}>Diarios</p>
          <div
            style={{
              alignItems: "center",
              display: "flex",
              flexDirection: "column",
            }}
          >
            <Table
              sx={{ minWidth: 650 }}
              size="small"
              aria-label="a dense table"
            >
              <TableHead>
                <TableRow>
                  <TableCell align="center">Data</TableCell>
                  <TableCell align="center">Conteúdo</TableCell>
                  <TableCell align="center">Observações</TableCell>
                </TableRow>
              </TableHead>
              <TableBody>
                {diarioTurma.map((row, index) => (
                    <TableRow key={index} >
                      <TableCell component="th" scope="row" align="center">
                        {row.dataDiario}
                      </TableCell>
                      <TableCell align="center">{row.conteudo}</TableCell>
                      <TableCell align="center">{row.observacao}</TableCell>
                    </TableRow>
                  ))}
              </TableBody>
            </Table>
            <Button
              variant="outlined"
              onClick={() => router.push({pathname: "diario/cadastro", query: {turma_id: router.query.id}})}
              sx={{ alignSelf: "center" }}
            >
              Cadastrar
            </Button>
          </div>
        </main>
      </Layout>
    </div>
  );
}
