import Head from "next/head";
import { useRouter } from "next/router";
import styles from "../../../styles/Home.module.css";
import Grid from "@mui/material/Grid";
import Layout from "../../../component/layout";
import apiRequest from "../../../util/apiRequest";
import React, { useState, ChangeEvent, useEffect } from "react";
import Table from "@mui/material/Table";
import TableHead from "@mui/material/TableHead";
import TableRow from "@mui/material/TableRow";
import TableCell from "@mui/material/TableCell";
import TableBody from "@mui/material/TableBody";
import Button from "@mui/material/Button";
import IconButton from "@mui/material/IconButton";
import ModeEditIcon from "@mui/icons-material/ModeEdit";
import DeleteIcon from "@mui/icons-material/Delete";
import Link from "@mui/material/Link";

export default function PortalDoCurso() {
  const [diario] = useState<any>([]);
  const router = useRouter();
  // useEffect(() => {
  //   if (listaCursos) {
  //     setCurso(listaCursos);
  //   }
  //   console.log(listaCursos);
  //   console.log(error);
  //   //erros
  // }, []);

  return (
    <div className={styles.container}>
      <Head>
        <title>Galdi</title>
        <meta name="description" content="Generated by meio a meio" />
      </Head>
      <Layout>
        <main className={styles.main}>
          <p className={styles.description}>Diario</p>
          <div
            style={{
              alignItems: "center",
              display: "flex",
              flexDirection: "column",
            }}
          >
            <Table
              sx={{ minWidth: 650 }}
              size="small"
              aria-label="a dense table"
            >
              <TableHead>
                <TableRow>
                  <TableCell align="left">Data</TableCell>
                  <TableCell align="left">Turma</TableCell>
                  <TableCell align="left">Conteúdo</TableCell>
                  <TableCell align="left">Observações</TableCell>
                </TableRow>
              </TableHead>
              <TableBody>
                {diario.map((row, index) => (
                    <TableRow key={index} >
                      <TableCell component="th" scope="row">
                        {row.id}
                      </TableCell>
                      <TableCell align="center">{row.nome}</TableCell>
                      <TableCell align="center">{row.turma}</TableCell>
                      <TableCell align="center">{row.conteudo}</TableCell>
                      <TableCell align="center">{row.observacoes || ""}</TableCell>
                      <TableCell align="center">
                        <IconButton
                          color="primary"
                          aria-label="edit"
                          component="label"
                          onClick={() => router.push("/atividade/portal")}
                        >
                          <ModeEditIcon />
                        </IconButton>
                        <IconButton
                          color="primary"
                          aria-label="delete"
                          component="label"
                        >
                          <DeleteIcon />
                        </IconButton>
                      </TableCell>
                    </TableRow>
                  ))}
              </TableBody>
            </Table>
            <Button
              variant="outlined"
              onClick={() => router.push("cadastro")}
              sx={{ alignSelf: "center" }}
            >
              Cadastrar
            </Button>
            <Grid container justifyContent="center">
              <Grid item>
                <Link href="/turma/detalhesTeste" variant="body2">
                  Retornar ao Menu Principal
                </Link>
              </Grid>
            </Grid>
          </div>
        </main>
      </Layout>
    </div>
  );
}
