import type { NextPage } from 'next'
import Head from 'next/head'
import { useRouter } from 'next/router'
import Image from 'next/image'
import styles from '../../styles/Home.module.css'
import Link from 'next/link'


const PortalDeCadastro: NextPage = () => {
    //acessa qualquer post que quiser no blog
    const router = useRouter()
    return (
      <div className={styles.container}>
        <Head>
          <title>Galdi</title>
          <meta name="description" content="Generated by meio a meio" />
          <link rel="icon" href="/images/icon.png" />
        </Head>
  
        <main className={styles.main}>
          <h1 className={styles.title}>
            Cadastre-se aqui
          </h1>
  
          <p className={styles.description}>
            Selecione a opção de cadastro:
            {/* <code className={styles.code}>pages/index.tsx</code> */}
          </p>
          <div className={styles.grid}>
          <Link href="/administrador/cadastro">
            <a
              className={styles.card}
            >
              <h2> Administrador &rarr;</h2>
              <p>
                Administrador, cadastre-se aqui
              </p>
            </a>
            </Link>
            <Link href="/professor/cadastro">
            <a
              className={styles.card}
            >
              <h2>Professor &rarr;</h2>
              <p>
                Professor, cadastre-se aqui
              </p>
            </a>
            </Link>
          </div>
        </main>
  
        <footer className={styles.footer}>
          <a
            href="https://mdsreq-fga-unb.github.io/2022.1-Meio-a-Meio/"
            target="_blank"
            rel="noopener noreferrer"
          >
            Copyright © Meio a Meio
          </a>
        </footer>
      </div>
    )
}

export default PortalDeCadastro    
