import type { NextPage } from 'next'
import Head from 'next/head'
import { useRouter } from 'next/router'
import Image from 'next/image'
import styles from '../../styles/Home.module.css'
import Link from 'next/link'


const Inicio: NextPage = () => {
    //acessa qualquer post que quiser no blog
    const router = useRouter()
    return (
      <div className={styles.container}>
        <Head>
          <title>Galdi</title>
          <meta name="description" content="Generated by meio a meio" />
          <link rel="icon" href="/images/icon.png" />
        </Head>
  
        <main className={styles.main}>
          <h1 className={styles.title}>
            Bem vindo(a).
          </h1>
  
          <p className={styles.description}>
            Selecione a opção desejada
            {/* <code className={styles.code}>pages/index.tsx</code> */}
          </p>
          <div className={styles.grid}>
          {/* <Link href="/aluno/portal">
            <a
              className={styles.card}
            >
              <h2> Alunos &rarr;</h2>
              <p>
                Informações sobre os alunos
              </p>
            </a>
            </Link>
            <Link href="/curso/portal">
            <a
              className={styles.card}
            >
              <h2>Cursos &rarr;</h2>
              <p>
              Informações sobre os cursos
              </p>
            </a>
            </Link>
            <Link href="/disciplina/portal">
            <a
              className={styles.card}
            >
              <h2>Disciplinas &rarr;</h2>
              <p>Informações sobre as disciplinas</p>
            </a>
            </Link> */}
            <Link href="/professor/visualizarPerfil">
            <a
              className={styles.card}
            >
              <h2>Perfil &rarr;</h2>
              <p>
              Veja aqui as informações do seu perfil no Galdi
              </p>
            </a>
            </Link>
            <Link href="/professor/editarPerfil">
            <a
              className={styles.card}
            >
              <h2>Edite seu perfil &rarr;</h2>
              <p>
              Edite aqui as suas informações de cadastro
              </p>
            </a>
            </Link>
            <Link href="/turma/portal">
            <a
              className={styles.card}
            >
              <h2>Turmas &rarr;</h2>
              <p>
              Informações sobre as turmas
              </p>
            </a>
            </Link>
          </div>
        </main>
  
        <footer className={styles.footer}>
          <a
            href="https://mdsreq-fga-unb.github.io/2022.1-Meio-a-Meio/"
            target="_blank"
            rel="noopener noreferrer"
          >
            Copyright © Meio a Meio
          </a>
        </footer>
      </div>
    )
}

export default Inicio    
