import * as React from "react";
import { useEffect } from "react";
import type { NextPage } from "next";
import Head from "next/head";
import { useRouter } from "next/router";
import Image from "next/image";
import styles from "../../styles/Home.module.css";
import Link from "next/link";
import { styled, ThemeProvider, createTheme } from "@mui/material/styles";
import Paper from "@mui/material/Paper";
import GroupsIcon from "@mui/icons-material/Groups";
import ImportContactsIcon from "@mui/icons-material/ImportContacts";
import Public from "@mui/icons-material/Public";
import List from "@mui/material/List";
import ListItemIcon from "@mui/material/ListItemIcon";
import ListItemText from "@mui/material/ListItemText";
import Divider from "@mui/material/Divider";
import Box from "@mui/material/Box";
import Button from "@mui/material/Button";
import Typography from "@mui/material/Typography";
import Drawer, { DrawerProps } from "@mui/material/Drawer";
import LogoutOutlinedIcon from "@mui/icons-material/LogoutOutlined";
import FeedOutlinedIcon from "@mui/icons-material/FeedOutlined";
import NextLink from "next/link";
import { Selector as SelectorIcon } from "../../component/selector";
import { NavItem } from "../../component/nav-item";
import AccountCircleIcon from "@mui/icons-material/AccountCircle";
import AutoAwesomeMotionIcon from "@mui/icons-material/AutoAwesomeMotion";
import GroupIcon from "@mui/icons-material/Group";
import CabinIcon from "@mui/icons-material/Cabin";
import AppBar from "@mui/material/AppBar";

const data = [
  {
    href: "/docente/portal",
    icon: <CabinIcon fontSize="small" />,
    title: "Início",
  },
  {
    href: "/",
    icon: <AccountCircleIcon fontSize="small" />,
    title: "Seu Perfil",
  },
  {
    href: "/aluno/portal",
    icon: <GroupIcon fontSize="small" />,
    title: "Alunos",
  },
  {
    href: "/professor/portal",
    icon: <GroupsIcon fontSize="small" />,
    title: "Professores",
  },
  {
    href: "/curso/portal",
    icon: <ImportContactsIcon fontSize="small" />,
    title: "Cursos",
  },
  {
    href: "/turma/portal",
    icon: <Public fontSize="small" />,
    title: "Turmas",
  },
  {
    href: "/disciplina/portal",
    icon: <FeedOutlinedIcon fontSize="small" />,
    title: "Disciplinas",
  },
  {
    href: "/atividade/portal",
    icon: <AutoAwesomeMotionIcon fontSize="small" />,
    title: "Atividades",
  },
];

const FireNav = styled(List)<{ component?: React.ElementType }>({
  "& .MuiListItemButton-root": {
    paddingLeft: 24,
    paddingRight: 24,
  },
  "& .MuiListItemIcon-root": {
    minWidth: 0,
    marginRight: 16,
  },
  "& .MuiSvgIcon-root": {
    fontSize: 20,
  },
});

export default function Inicio(props) {
  const router = useRouter();
  const { ...other } = props;
  const [open, setOpen] = React.useState(true);
  const { close, onClose } = props;
  useEffect(
    () => {
      if (!router.isReady) {
        return;
      }

      if (close) {
        onClose?.();
      }
    },
    // eslint-disable-next-line react-hooks/exhaustive-deps
    [router.asPath]
  );
  return (
    <ThemeProvider
      theme={createTheme({
        components: {
          MuiListItemButton: {
            defaultProps: {
              disableTouchRipple: true,
            },
          },
        },
        palette: {
          mode: "light",
          primary: { main: "rgb(0, 0, 0)" },
          background: { paper: "rgb(245, 235, 235)" },
        },
      })}
    >
      <header>Ca</header>
      <Head>
        <title>Galdi</title>
        <meta name="description" content="Generated by meio a meio" />
        <link rel="icon" href="/images/icon.png" />
      </Head>
      <Paper elevation={0} sx={{ width: 1000 }}>
        <AppBar
          position="static"
          color="default"
          elevation={0}
          sx={{ borderBottom: "1px solid rgba(0, 0, 0, 0.12)" }}
        >
            <FireNav component="nav" disablePadding>
              <Drawer variant="permanent" {...other}>
                <Box
                  sx={{
                    display: "flex",
                    flexDirection: "column",
                    height: "100%",
                    width: 250,
                  }}
                >
                  <div>
                    <Box sx={{ p: 4.5, display: "flex" }}>
                      <ListItemIcon sx={{ fontSize: 25 }}>⚕️</ListItemIcon>
                      <ListItemText
                        primary="Galdi"
                        primaryTypographyProps={{
                          fontSize: 25,
                          fontWeight: "medium",
                          letterSpacing: 0.3,
                        }}
                      />
                    </Box>
                    <Box sx={{ px: 2 }}>
                      <Box
                        sx={{
                          alignItems: "center",
                          backgroundColor: "rgba(0, 0, 0, 0.1)",
                          cursor: "pointer",
                          display: "flex",
                          justifyContent: "space-between",
                          px: 3,
                          py: "11px",
                          borderRadius: 1,
                        }}
                      >
                        <div>
                          <Typography
                            color="inherit"
                            variant="subtitle1"
                            align="center"
                          >
                            2022/2
                          </Typography>
                        </div>
                        <SelectorIcon
                          sx={{
                            color: "neutral.500",
                            width: 14,
                            height: 14,
                          }}
                        />
                      </Box>
                    </Box>
                  </div>
                  <Divider
                    sx={{
                      borderColor: "#2D3748",
                      my: 3,
                    }}
                  />
                  <Box sx={{ flexGrow: 1 }}>
                    {open &&
                      data.map((item) => (
                        <NavItem
                          key={item.title}
                          icon={item.icon}
                          href={item.href}
                          title={item.title}
                        />
                      ))}
                  </Box>
                  <NextLink href="/" passHref>
                    <Button
                      color="primary"
                      component="a"
                      endIcon={<LogoutOutlinedIcon />}
                      fullWidth
                      sx={{ mt: 2 }}
                      variant="contained"
                    >
                      Sair
                    </Button>
                  </NextLink>
                </Box>
              </Drawer>
            </FireNav>
        </AppBar>
      </Paper>
      <footer className={styles.footer}>
        <a
          href="https://github.com/mdsreq-fga-unb/2022.1-Meio-a-Meio"
          target="_blank"
          rel="noopener noreferrer"
        >
          Copyright © Meio a Meio
        </a>
      </footer>
    </ThemeProvider>
  );
}
