import * as React from "react";
import { useEffect } from "react";
import type { NextPage } from "next";
import Head from "next/head";
import { useRouter } from "next/router";
import Image from "next/image";
import styles from "../../styles/Home.module.css";
import Link from "next/link";
import { styled, ThemeProvider, createTheme } from "@mui/material/styles";
import Paper from "@mui/material/Paper";
import People from "@mui/icons-material/People";
import Dns from "@mui/icons-material/Dns";
import PermMedia from "@mui/icons-material/PermMedia";
import Public from "@mui/icons-material/Public";
import List from "@mui/material/List";
import ListItemButton from "@mui/material/ListItemButton";
import ListItemIcon from "@mui/material/ListItemIcon";
import ListItemText from "@mui/material/ListItemText";
import Divider from "@mui/material/Divider";
import Settings from "@mui/icons-material/Settings";
import ArrowRight from "@mui/icons-material/ArrowRight";
import Tooltip from "@mui/material/Tooltip";
import IconButton from "@mui/material/IconButton";
import ListItem from "@mui/material/ListItem";
import Home from "@mui/icons-material/Home";
import KeyboardArrowDown from "@mui/icons-material/KeyboardArrowDown";
import Box from "@mui/material/Box";
import Button from "@mui/material/Button";
import Typography from "@mui/material/Typography";
import Drawer, { DrawerProps } from "@mui/material/Drawer";
import LogoutOutlinedIcon from "@mui/icons-material/LogoutOutlined";
import FeedOutlinedIcon from "@mui/icons-material/FeedOutlined";
import NextLink from "next/link";
import { Selector as SelectorIcon } from "./selector";
import { NavItem } from "./nav-item";
import PropTypes from 'prop-types';


const data = [
  //   {
  //     href: '/',
  //     icon: (<ChartBarIcon fontSize="small" />),
  //     title: 'Dashboard'
  //   },
    {
      href: '/aluno/portal',
      icon: (<People fontSize="small" />),
      title: 'Alunos'
    },
    {
      href: '/curso/portal',
      icon: (<Dns fontSize="small" />),
      title: 'Cursos'
    },
    {
      href: '/disciplina/portal',
      icon: (<FeedOutlinedIcon fontSize="small" />),
      title: 'Disciplinas'
    },
    {
      href: '/turma/portal',
      icon: (<Public fontSize="small" />),
      title: 'Turmas'
    },
  //   {
  //     href: '/settings',
  //     icon: (<CogIcon fontSize="small" />),
  //     title: 'Settings'
  //   },
  ];

const FireNav = styled(List)<{ component?: React.ElementType }>({
  "& .MuiListItemButton-root": {
    paddingLeft: 24,
    paddingRight: 24,
  },
  "& .MuiListItemIcon-root": {
    minWidth: 0,
    marginRight: 16,
  },
  "& .MuiSvgIcon-root": {
    fontSize: 20,
  },
});

export default function Inicio(props) {
  const router = useRouter();
  const { ...other } = props;
  const [open, setOpen] = React.useState(true);
  const { close, onClose } = props;
  useEffect(
    () => {
      if (!router.isReady) {
        return;
      }

      if (close) {
        onClose?.();
      }
    },
    // eslint-disable-next-line react-hooks/exhaustive-deps
    [router.asPath]
  );
  return (
    <ThemeProvider
      theme={createTheme({
        components: {
          MuiListItemButton: {
            defaultProps: {
              disableTouchRipple: true,
            },
          },
        },
        palette: {
          mode: "light",
          primary: { main: "rgb(0, 0, 0)" },
          background: { paper: "rgb(245, 235, 235)" },
        },
      })}
    >
      <header>Ca</header>
      <Head>
        <title>Galdi</title>
        <meta name="description" content="Generated by meio a meio" />
        <link rel="icon" href="/images/icon.png" />
      </Head>
      <Paper elevation={0} sx={{ maxWidth: 256 }}>
        <FireNav component="nav" disablePadding>
          <Drawer variant="permanent" {...other}>
            <Box
              sx={{
                display: "flex",
                flexDirection: "column",
                height: "100%",
              }}
            >
              <div>
                <Box sx={{ p: 3 }}>
                  <a>
                    <ListItemButton component="a">
                      <ListItemIcon sx={{ fontSize: 25 }}>⚕️</ListItemIcon>
                      <ListItemText
                        sx={{ my: 2, mx: 4 }}
                        primary="Galdi"
                        primaryTypographyProps={{
                          fontSize: 25,
                          fontWeight: "medium",
                          letterSpacing: 0.5,
                        }}
                      />
                    </ListItemButton>
                  </a>
                </Box>
                <Box sx={{ px: 2 }}>
                  <Box
                    sx={{
                      alignItems: "center",
                      backgroundColor: "rgba(0, 0, 0, 0.1)",
                      cursor: "pointer",
                      display: "flex",
                      justifyContent: "space-between",
                      px: 3,
                      py: "11px",
                      borderRadius: 1,
                    }}
                  >
                    <div>
                      <Typography
                        color="inherit"
                        variant="subtitle1"
                        align="center"
                      >
                        2022/2
                      </Typography>
                    </div>
                    <SelectorIcon
                      sx={{
                        color: "neutral.500",
                        width: 14,
                        height: 14,
                      }}
                    />
                  </Box>
                </Box>
              </div>
              <Divider
                sx={{
                  borderColor: "#2D3748",
                  my: 3,
                }}
              />
              <Box sx={{ flexGrow: 1 }}>
                {open &&
                  data.map((item) => (
                    <NavItem
                      key={item.title}
                      icon={item.icon}
                      href={item.href}
                      title={item.title}
                    />
                    // <ListItemButton
                    //   key={item.label}
                    //   sx={{
                    //     display: "flex",
                    //     py: 0,
                    //     minHeight: 75,
                    //   }}
                    // >
                    //   <ListItemIcon sx={{ color: "inherit" }}>
                    //     {item.icon}
                    //   </ListItemIcon>

                    //   <ListItemText
                    //     primary={item.label}
                    //     primaryTypographyProps={{
                    //       fontSize: 14,
                    //       fontWeight: "medium",
                    //     }}
                    //   />
                    // </ListItemButton>
                  ))}
              </Box>
              <NextLink href="/" passHref>
                <Button
                  color="primary"
                  component="a"
                  endIcon={<LogoutOutlinedIcon />}
                  fullWidth
                  sx={{ mt: 2 }}
                  variant="contained"
                >
                  Sair
                </Button>
              </NextLink>
            </Box>
          </Drawer>
        </FireNav>
      </Paper>
      <footer className={styles.footer}>
        <a
          href="https://github.com/mdsreq-fga-unb/2022.1-Meio-a-Meio"
          target="_blank"
          rel="noopener noreferrer"
        >
          Copyright © Meio a Meio
        </a>
      </footer>
    </ThemeProvider>
  );
};


