import * as React from "react";
import Head from "next/head";
import styles from "../../styles/Home.module.css";
import Layout from '../../component/layout'
export default function Inicio() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Galdi</title>
        <meta name="description" content="Generated by meio a meio" />
      </Head>
      <Layout>
      <main className={styles.main}>
      <h1 className={styles.title}>
            Bem vindo(a) ao Galdi.
          </h1>
      </main>
      </Layout>
      </div>
  );
}