import Head from "next/head";
import styles from "../../styles/Home.module.css";
import Layout from "../../component/layout";
import apiRequest from "../../util/apiRequest";
import { useRouter } from "next/router";
import React, { useState, ChangeEvent, useEffect } from "react";
import Table from "@mui/material/Table";
import TableHead from "@mui/material/TableHead";
import TableRow from "@mui/material/TableRow";
import TableCell from "@mui/material/TableCell";
import TableBody from "@mui/material/TableBody";

export default function PerfilAdministrador() {
  const [administrador, setAdm] = useState<any>([]);
  const router = useRouter();
  async function getDadosAdm(){
    const resDadosAdm = await apiRequest.get("administrador/" + router.query.id);
    if (resDadosAdm.data) {
      setAdm(resDadosAdm.data);
    }
  }
  useEffect(() => {
    getDadosAdm();
  }, []);

  return (
    <div className={styles.container}>
      <Head>
        <title>Galdi</title>
        <meta name="description" content="Generated by meio a meio" />
      </Head>
      <Layout>
        <main className={styles.main}>
          <p className={styles.description}>Seu Perfil</p>
          <div
            style={{
              alignItems: "center",
              display: "flex",
              flexDirection: "column",
            }}
          >
            <Table
              sx={{ minWidth: 650 }}
              size="small"
              aria-label="a dense table"
            >
              <TableHead>
                <TableRow sx={{ display: "flex", flexDirection: "column" }}>
                  <TableCell align="left">Nome</TableCell>
                  <TableCell align="left">Matrícula</TableCell>
                  <TableCell align="left">Celular</TableCell>
                  <TableCell align="left">CPF</TableCell>
                  <TableCell align="left">Data de Nascimento</TableCell>
                  <TableCell align="left">RG/RNE</TableCell>
                  <TableCell align="left">Email</TableCell>
                </TableRow>
              </TableHead>
              <TableBody>
                {administrador.map((row, index) => (
                  <TableRow key={index} sx={{ display: "flex", flexDirection: "column" }}>
                    <TableCell align="right">{row.nome_completo}</TableCell>
                    <TableCell align="right">{row.matricula || ""}</TableCell>
                    <TableCell align="right">{row.celular}</TableCell>
                    <TableCell align="right">{row.cpf}</TableCell>
                    <TableCell align="right">
                      {row.data_de_nascimento}
                    </TableCell>
                    <TableCell align="right">{row.rg_rne}</TableCell>
                    <TableCell align="right">{row.email}</TableCell>
                  </TableRow>
                ))}
              </TableBody>
            </Table>
          </div>
        </main>
      </Layout>
    </div>
  );
}
