import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

const Cadastro: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Cadastro</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          <a href="https://nextjs.org">Cadastro</a>
        </h1>

        <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>pages/index.tsx</code>
        </p>
      </main>
    </div>
  )
}

export default Cadastro
/* cadastro pessoa:
    nome
    sobrenome
    dataNascimento
    crm
    uf
    especializacao
    matricula - gerada aleatoriamente (campo nao editavel)
    senha
    confirmaçao de senha
    */ 
