import Typography from "@mui/material/Typography";
import { createTheme, ThemeProvider } from "@mui/material/styles";
import Link from "@mui/material/Link";
import Container from "@mui/material/Container";
import Box from "@mui/material/Box";
import Head from "next/head";
import CssBaseline from "@mui/material/CssBaseline";
import Grid from "@mui/material/Grid";
import { useRouter } from "next/router";
import React, { useState, ChangeEvent } from "react";
import TextField from "@mui/material/TextField";
import Button from "@mui/material/Button";
import RadioGroup from "@mui/material/RadioGroup";
import FormControlLabel from "@mui/material/FormControlLabel";
import Radio from "@mui/material/Radio";
import FormControl from "@mui/material/FormControl";
import Select, { SelectChangeEvent } from "@mui/material/Select";
import MenuItem from "@mui/material/MenuItem";
import InputLabel from "@mui/material/InputLabel";
import Checkbox from "@mui/material/Checkbox";

const theme = createTheme();

export default function CadastroAtividades() {
  const [data, setData] = useState<any>({});
  const [errors, setErrors] = useState<any>({});
  const router = useRouter();
  const [professor, setProfessor] = React.useState("");
  const handleSubmit = (event: React.FormEvent<HTMLFormElement>) => {
    event.preventDefault();
    if (handleCheckData()) {
      return;
    }
    router.push("/turma/listar");
  };
  const handleText = (e: ChangeEvent<HTMLInputElement>) => {
    const clearText = e.target.value.replace(/\d/, "");
    setData({ ...data, [e.target.name]: clearText });
    let tempErrors = errors;
    delete tempErrors[e.target.name];
    setErrors(tempErrors);
  };
  const handleChange = (event: SelectChangeEvent) => {
    setProfessor(event.target.value);
  };
  const handleCheckData = () => {
    const {
      nome_atividade,
      id_turma,
      nome_disciplina,
      nome_turma,
      nome_aluno,
      nota,
    } = data;
    let emptyFields: any = {};
    if (!nome_atividade || nome_atividade.length === 0) {
      emptyFields.nome_atividade = "Atividade Inválida";
    }
    if (!id_turma || id_turma.length === 0) {
      emptyFields.id_turma = "Turma Inválida";
    }
    if (!nome_disciplina || nome_disciplina.length === 0) {
      emptyFields.nome_disciplina = "Disciplina Inválida";
    }
    if (!nome_aluno || nome_aluno.length === 0) {
      emptyFields.nome_aluno = "Aluno Inválido";
    }
    if (!nome_turma || nome_turma.length === 0) {
      emptyFields.nome_turma = "Turma Inválida";
    }
    if (!nota || nota.length === 0) {
      emptyFields.nota = "Nota Inválida";
    }
    if (Object.keys(emptyFields).length > 0) {
      setErrors(emptyFields);
      return 1;
    }
    return 0;
  };
  return (
    <ThemeProvider theme={theme}>
      <Container component="main" maxWidth="lg">
        <CssBaseline />
        <Box
          sx={{
            marginTop: 8,
            display: "flex",
            flexDirection: "column",
            alignItems: "center",
          }}
        >
          <div>
            <Head>
              <title>Galdi</title>
              <meta name="description" content="Generated by meio a meio" />
              <link rel="icon" href="/images/icon.png" />
            </Head>
            {/* <Image src= "/images/logo.jpeg" width= '600px' height= '150px'/> */}
          </div>
          <Typography component="h1" variant="h5">
            Cadastro de Atividades
          </Typography>
          <Box
            component="form"
            noValidate
            onSubmit={handleSubmit}
            sx={{ mt: 3 }}
          >
            <Grid container spacing={1}>
              <Grid item xs={4}>
                <TextField
                  required
                  error={errors.nome_atividade ? true : false}
                  helperText={errors.nome_atividade || null}
                  fullWidth
                  id="nome_atividade"
                  label="Atividade"
                  name="nome_atividade"
                  autoComplete="nome_atividade"
                  onChange={handleText}
                  value={data ? data.nome_atividade : ""}
                />
              </Grid>
              <Grid item xs={4}>
                <FormControl sx={{ m: 0, minWidth: 200 }}>
                  <InputLabel id="id_turma" required>
                    Turma
                  </InputLabel>
                  <Select
                    labelId="demo-simple-select-helper-label"
                    id="demo-simple-select-helper"
                    value={data ? data.id_turma : ""}
                    onChange={handleChange}
                    error={errors.id_turma ? true : false}
                  >
                    <MenuItem value={1}>A</MenuItem>
                    <MenuItem value={2}>B</MenuItem>
                    <MenuItem value={3}>C</MenuItem>
                  </Select>
                </FormControl>
              </Grid>
              <Grid item xs={2.5}>
                <FormControl fullWidth>
                  <FormControlLabel
                    control={<Checkbox defaultChecked />}
                    label="Prova?"
                    onChange={(e) => setData({ ...data, tipo: e.target.value })}
                    value={data ? data.tipo : null}
                  />
                </FormControl>
              </Grid>
              <Button
                type="submit"
                fullWidth
                variant="contained"
                sx={{ mt: 3, mb: 2 }}
              >
                Cadastrar Atividade
              </Button>
              <Grid container justifyContent="center">
                <Grid item>
                  <Link href="/atividade/portal" variant="body2">
                    Retornar ao Menu Principal
                  </Link>
                </Grid>
              </Grid>
            </Grid>
          </Box>
        </Box>
      </Container>
    </ThemeProvider>
  );
}
