import Head from 'next/head'
import { useRouter } from 'next/router'
import styles from '../../styles/Home.module.css'
import Link from 'next/link'
import Layout from '../../component/layout'


export default function PortalDaTurma() {
    const router = useRouter()
    return (
      <div className={styles.container}>
        <Head>
          <title>Galdi</title>
          <meta name="description" content="Generated by meio a meio" />
          <link rel="icon" href="/images/icon.png" />
        </Head>
        <Layout>
        <main className={styles.main}>
          <h1 className={styles.title}>
            Atividades
          </h1>

          <div className={styles.grid}>
            <Link href="/atividade/cadastroNotas">
            <a
              className={styles.card}
            >
              <h2>Cadastrar Notas &rarr;</h2>
              <p>
              Cadastre as notas das atividades aqui
              </p>
            </a>
            </Link>
            <Link href="/atividade/cadastroAtividades">
            <a
              className={styles.card}
            >
              <h2>Cadastrar Atividades &rarr;</h2>
              <p>
              Cadastre as atividades aqui
              </p>
            </a>
            </Link>
            <Link href="/atividade/cadastroDiarioAula">
            <a
              className={styles.card}
            >
              <h2>Cadastrar Diario de Aula &rarr;</h2>
              <p>
                Cadastre os diarios aqui
              </p>
            </a>
            </Link>
            <Link href="/atividade/visualizarNotasAtividades">
            <a
              className={styles.card}
            >
              <h2>Atividades &rarr;</h2>
              <p>
                Veja suas atividades registradas aqui
              </p>
            </a>
            </Link>
            <Link href="/atividade/visualizarNotasAvaliacoes">
            <a
              className={styles.card}
            >
              <h2>Avaliações &rarr;</h2>
              <p>
                Veja suas avaliações registradas aqui
              </p>
            </a>
            </Link>
            <Link href="/atividade/visualizarDiario">
            <a
              className={styles.card}
            >
              <h2>Diários &rarr;</h2>
              <p>
                Veja seus diários registrados aqui
              </p>
            </a>
            </Link>
          </div>
        </main>
        </Layout>
      </div>
    )
}

