import Head from "next/head";
import { useRouter } from "next/router";
import styles from "../../styles/Home.module.css";
import Grid from "@mui/material/Grid";
import Layout from "../../component/layout";
import apiRequest from "../../util/apiRequest";
import React, { useState, ChangeEvent, useEffect } from "react";
import Table from "@mui/material/Table";
import TableHead from "@mui/material/TableHead";
import TableRow from "@mui/material/TableRow";
import TableCell from "@mui/material/TableCell";
import TableBody from "@mui/material/TableBody";
import Button from "@mui/material/Button";
import IconButton from "@mui/material/IconButton";
import ModeEditIcon from "@mui/icons-material/ModeEdit";
import DeleteIcon from "@mui/icons-material/Delete";
import Link from "@mui/material/Link";

export default function PortalDoCurso() {
  const [diario] = useState<any>([]);
  const router = useRouter();
  // useEffect(() => {
  //   if (listaCursos) {
  //     setCurso(listaCursos);
  //   }
  //   console.log(listaCursos);
  //   console.log(error);
  //   //erros
  // }, []);

  return (
    <div className={styles.container}>
      <Head>
        <title>Galdi</title>
        <meta name="description" content="Generated by meio a meio" />
        <link rel="icon" href="/images/icon.png" />
      </Head>
      <Layout>
        <main className={styles.main}>
          <p className={styles.description}>Diario</p>
          <div
            style={{
              alignItems: "center",
              display: "flex",
              flexDirection: "column",
            }}
          >
            <Table
              sx={{ minWidth: 650 }}
              size="small"
              aria-label="a dense table"
            >
              {/* <TableHead>
                  <TableRow>
                    <TableCell>Id</TableCell>
                    <TableCell align="center">Data</TableCell>
                    <TableCell align="center">Turma</TableCell>
                    <TableCell align="center">Professor</TableCell>
                    <TableCell align="center">Materia</TableCell>
                    <TableCell align="center">Conteúdo</TableCell>
                    <TableCell align="center">Observações</TableCell>
                  </TableRow>
                </TableHead> */}
              <TableBody>
                <TableRow>
                  <TableCell align="left">Data</TableCell>
                </TableRow>
                <TableRow>
                  <TableCell align="left">Turma</TableCell>
                </TableRow>
                <TableRow>
                  <TableCell align="left">Professor</TableCell>
                </TableRow>
                <TableRow>
                  <TableCell align="left">Materia</TableCell>
                </TableRow>
                <TableRow>
                  <TableCell align="left">Conteúdo</TableCell>
                </TableRow>
                <TableRow>
                  <TableCell align="left">Observações</TableCell>
                </TableRow>

                {/* {diario.map((row, index) => (
                    <TableRow key={index}>
                      <TableCell component="th" scope="row">
                        {row.id}
                      </TableCell>
                      <TableCell align="center">{row.nome}</TableCell>
                      <TableCell align="center">{row.unidade || ""}</TableCell>
                      <TableCell align="center">
                        <IconButton
                          color="primary"
                          aria-label="edit"
                          component="label"
                          onClick={() => router.push("/curso/editar")}
                        >
                          <ModeEditIcon />
                        </IconButton>
                        <IconButton
                          color="primary"
                          aria-label="delete"
                          component="label"
                        >
                          <DeleteIcon />
                        </IconButton>
                      </TableCell>
                    </TableRow>
                  ))} */}
              </TableBody>
            </Table>
            <Grid container justifyContent="center">
                <Grid item>
                  <Link href="/atividade/portal" variant="body2">
                    Retornar ao Menu Principal
                  </Link>
                </Grid>
              </Grid>
          </div>
        </main>
      </Layout>
    </div>
  );
}
