import Head from 'next/head'
import { useRouter } from 'next/router'
import styles from '../../../styles/Home.module.css'
import Link from 'next/link'
import Layout from '../../../component/layout'

export default function PortalDaPresenca () {
    const router = useRouter()

    return (
      <div className={styles.container}>
        <Head>
          <title>Galdi</title>
          <meta name="description" content="Generated by meio a meio" />
          <link rel="icon" href="/images/icon.png" />
        </Head>
        <Layout>
        <main className={styles.main}>  
          <div className={styles.grid}>
          <Link href="/turma/listaPresenca/cadastro">
            <a
              className={styles.card}
            >
              <h2>Cadastrar &rarr;</h2>
              <p>
                Cadastrar nova lista de presença
              </p>
            </a>
            </Link>
            <Link href="/turma/listaPresenca/visualizar">
            <a
              className={styles.card}
            >
              <h2>Visualizar &rarr;</h2>
              <p>
                Verificar todas as listas de presneça já cadastradas
              </p>
            </a>
            </Link>
          </div>
        </main>
        </Layout>
      </div>
    )
}