import Typography from "@mui/material/Typography";
import { createTheme, ThemeProvider } from "@mui/material/styles";
import Link from "@mui/material/Link";
import Container from "@mui/material/Container";
import Box from "@mui/material/Box";
import Head from "next/head";
import CssBaseline from "@mui/material/CssBaseline";
import Grid from "@mui/material/Grid";
import { useRouter } from "next/router";
import React, { useState, ChangeEvent, useEffect } from "react";
import TextField from "@mui/material/TextField";
import Button from "@mui/material/Button";
import RadioGroup from "@mui/material/RadioGroup";
import FormControlLabel from "@mui/material/FormControlLabel";
import Radio from "@mui/material/Radio";
import FormControl from "@mui/material/FormControl";
import Select, { SelectChangeEvent } from "@mui/material/Select";
import MenuItem from "@mui/material/MenuItem";
import InputLabel from "@mui/material/InputLabel";
import {apiRequest} from "../../../util/apiRequest";
import Alert from "@mui/material/Alert";
import Collapse from "@mui/material/Collapse";
import IconButton from "@mui/material/IconButton";
import CloseIcon from "@mui/icons-material/Close";
import FormHelperText from "@mui/material/FormHelperText";
const theme = createTheme();

export default function CadastroAlunosEmTurmas() {
  const [data, setData] = useState<any>({});
  const [errors, setErrors] = useState<any>({});
  const router = useRouter();
  const [aluno, setAluno] = useState<any>([]);
  const [open, setOpen] = useState(false);
  const [close, setClose] = useState(false);
  const [errorMessage, setErrorMessage] = useState<any>("");

  async function getAlunoTurma() {
    const resAluno = await apiRequest.get("aluno");
  const resTurma = await apiRequest.get("turma/" + router.query.turma_id);
    if (resAluno.data) {
      setAluno(resAluno.data);
    }
    setData(resTurma.data)
  }
  useEffect(() => {
    getAlunoTurma();
  }, []);


  const handleSubmit = (event: React.FormEvent<HTMLFormElement>) => {
    event.preventDefault();
    if (handleCheckData()) {
      setClose(true);
      return;
    }
    apiRequest
      .post("turma/addAluno/" + router.query.turma_id, { ...data, turma_id: data.id})
      .then((result) => {
        setOpen(true);
        router.back();
      })
      .catch((err) => {
        setErrorMessage(err.response.data.message);
        setClose(true);
      });
  };
  const handleText = (e: ChangeEvent<HTMLInputElement>) => {
    setData({...data,[e.target.name]: e.target.value});
  };

  const handleCheckData = () => {
    const { id } = data;
    let emptyFields: any = {};
    if (!id || id.length === 0) {
      emptyFields.id = "Aluno Inválido";
    }
    if (Object.keys(emptyFields).length > 0) {
      setErrors(emptyFields);
      return 1;
    }
    return 0;
  };
  return (
    <ThemeProvider theme={theme}>
      <Container component="main" maxWidth="lg">
        <CssBaseline />
        <Box
          sx={{
            marginTop: 8,
            display: "flex",
            flexDirection: "column",
            alignItems: "center",
          }}
        >
          <div>
            <Head>
              <title>Galdi</title>
              <meta name="description" content="Generated by meio a meio" />
            </Head>
          </div>
          <Typography component="h1" variant="h5">
            Cadastro de Alunos
          </Typography>
          <Box
            component="form"
            noValidate
            onSubmit={handleSubmit}
            sx={{ mt: 3 }}
          >
            <Grid container spacing={2}>
            <Grid item xs={4}>
                <FormControl sx={{ m: 0, minWidth: 150 }}>
                  <InputLabel id="id" required>
                    Aluno
                  </InputLabel>
                  <Select
                    required
                    fullWidth
                    error={errors.id ? true : false}
                    onChange={(e) =>
                      setData({ ...data, id: e.target.value })
                    }
                    label={"Aluno"}
                    value={data ? data.id : ""}
                  >
                    {aluno.map((i, index) => (
                      <MenuItem key={index} value={i.id}>
                        {i.nome_completo}
                      </MenuItem>
                    ))}
                  </Select>
                  <FormHelperText error>
                  {errors.id}
                </FormHelperText>
                </FormControl>
              </Grid>
              <Grid item xs={3}>
                <TextField
                disabled
                  fullWidth
                  id="nome_turma"
                  name="nome_turma"
                  autoComplete="nome_turma"
                  onChange={handleText}
                  value={data ? data.nome_turma : ""}
                />
              </Grid>
              <Button
                type="submit"
                fullWidth
                variant="contained"
                sx={{ mt: 3, mb: 2 }}
              >
                Cadastrar Aluno
              </Button>
              <Collapse in={open}>
              <Alert
              severity="success"
                action={
                  <IconButton
                    aria-label="close"
                    color="inherit"
                    size="small"
                    onClick={() => {
                      setOpen(false);
                    }}
                  >
                    <CloseIcon fontSize="inherit" />
                  </IconButton>
                }
                sx={{ mb: 2 }}
              >
                Cadastro realizado com sucesso!
              </Alert>
            </Collapse>
            <Collapse in={close}>
              <Alert
              severity="error"
                action={
                  <IconButton
                    aria-label="close"
                    color="inherit"
                    size="small"
                    onClick={() => {
                      setClose(false);
                    }}
                  >
                    <CloseIcon fontSize="inherit" />
                  </IconButton>
                }
                sx={{ mb: 2 }}
              >
                {errorMessage}
              </Alert>
            </Collapse> 
              <Grid container justifyContent="center">
                <Grid item>
                  <Link onClick={() => router.back()} variant="body2">
                    Retornar ao Menu Principal
                  </Link>
                </Grid>
              </Grid>
            </Grid>
          </Box>
        </Box>
      </Container>
    </ThemeProvider>
  );
}