import Head from "next/head";
import styles from "../../../styles/Home.module.css";
import Layout from "../../../component/layout";
import {apiRequest} from "../../../util/apiRequest";
import { useRouter } from "next/router";
import React, { useState, ChangeEvent, useEffect } from "react";
import Table from "@mui/material/Table";
import TableHead from "@mui/material/TableHead";
import TableRow from "@mui/material/TableRow";
import TableCell from "@mui/material/TableCell";
import TableBody from "@mui/material/TableBody";
import Button from "@mui/material/Button";
import IconButton from "@mui/material/IconButton";
import DeleteIcon from "@mui/icons-material/Delete";

export default function PortalDoAlunoNaTurma() {
  const [alunoTurma, setAlunoTurma] = useState<any>([]);
  const router = useRouter();
  async function getAlunosTurma(){
    
    const resAlunosTurma = await apiRequest.get("turma/alunos/" + router.query.detalhes);
    if (resAlunosTurma.data) {
      setAlunoTurma(resAlunosTurma.data);
    }
    
  }
  useEffect(() => {
    getAlunosTurma();
  }, []);

  const handleDelete = async(idAluno) => {
    apiRequest.delete(`turma/removeAluno/${router.query.detalhes}/${idAluno}`)
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Galdi</title>
        <meta name="description" content="Generated by meio a meio" />
      </Head>
      <Layout>
        <main className={styles.main}>
          <p className={styles.description}>Alunos</p>
          <div
            style={{
              alignItems: "center",
              display: "flex",
              flexDirection: "column",
            }}
          >
            <Table
              sx={{ minWidth: 650 }}
              size="small"
              aria-label="a dense table"
            >
              <TableHead>
                <TableRow>
                  <TableCell align="center">Nome</TableCell>
                  <TableCell align="center">Deletar</TableCell>
                </TableRow>
              </TableHead>
              <TableBody>
                {alunoTurma.map((row, index) => (
                  <TableRow key={index}>
                    <TableCell align="center">
                      {row.nome_completo}
                    </TableCell>
                    <TableCell align="center">
                      <IconButton
                        color="primary"
                        aria-label="delete"
                        component="label"
                        onClick={() => handleDelete(row.id)}
                      >
                        <DeleteIcon />
                      </IconButton>
                    </TableCell>
                  </TableRow>
                ))}
              </TableBody>
            </Table>
            <Button
              variant="outlined"
              onClick={() => router.push({pathname: "aluno/cadastro", query: {turma_id: router.query.detalhes}})}
              sx={{ alignSelf: "center" }}
            >
              Cadastrar
            </Button>
          </div>
        </main>
      </Layout>
    </div>
  );
}